---
# Join msg
msg: "Willkommen Auf Paincraft"
# Form settings
title: "Unsere Regeln"
content: "§l§b 1. Nicht Spammen \n §42. Keine CAPS! \n §93. Nicht Nach OP Fragen! \n §c4. Nicht Scammen!!! \n §e5. Nicht Betrügen" 
button: "Spielen"
...
